insert into package_type (id, package_type) values (1, 'Sub-segment RNAseq');
insert into package_type (id, package_type) values (2, 'Single-cell RNAseq');
insert into package_type (id, package_type) values (3, 'Single-nucleus RNAseq');
insert into package_type (id, package_type) values (4, 'Bulk RNAseq');
insert into package_type (id, package_type) values (5, 'DNA Methylation');
insert into package_type (id, package_type) values (6, 'Multiplex ISH');
insert into package_type (id, package_type) values (7, 'Sub-segmental Proteomics');
insert into package_type (id, package_type) values (8, 'Near-single-cell Proteomics');
insert into package_type (id, package_type) values (9, '3-D tissue imaging');
insert into package_type (id, package_type) values (10, 'Spatial Metabolomics');
insert into package_type (id, package_type) values (11, 'Inflammatory Cells');
insert into package_type (id, package_type) values (12, 'Other');
insert into package_type (id, package_type) values (14, 'Segmental miRNA');
