db.packages.update({"institution": "Broad (Michigan/Broad/Princeton TIS)"}, {$set: {"tisName": "Michigan/Broad/Princeton"}}, false, true)
db.packages.update({"institution": "EMBL (UTHSA/EMBL/PNNL/UCSD TIS)"}, {$set: {"tisName": "UTHSA/EMBL/PNNL/UCSD"}}, false, true)
db.packages.update({"institution": "Indiana (IU/OSU TIS)"}, {$set: {"tisName": "IU/OSU"}}, false, true)
db.packages.update({"institution": "Michigan (Michigan/Broad/Princeton TIS)"}, {$set: {"tisName": "Michigan/Broad/Princeton"}}, false, true)
db.packages.update({"institution": "OSU (IU/OSU TIS)"}, {$set: {"tisName": "IU/OSU"}}, false, true)
db.packages.update({"institution": "PNNL (UTHSA/EMBL/PNNL/UCSD TIS)"}, {$set: {"tisName": "UTHSA/EMBL/PNNL/UCSD"}}, false, true)
db.packages.update({"institution": "Princeton (Michigan/Broad/Princeton TIS)"}, {$set: {"tisName": "Michigan/Broad/Princeton"}}, false, true)
db.packages.update({"institution": "Stanford (UCSF/Stanford TIS)"}, {$set: {"tisName": "UCSF/Stanford"}}, false, true)
db.packages.update({"institution": "UCSD (UCSD/WashU TIS)"}, {$set: {"tisName": "UCSD/WashU"}}, false, true)
db.packages.update({"institution": "UCSD (UTHSA/EMBL/PNNL/UCSD TIS)"}, {$set: {"tisName": "UTHSA/EMBL/PNNL/UCSD"}}, false, true)
db.packages.update({"institution": "UCSF (UCSF/Stanford TIS)"}, {$set: {"tisName": "UCSF/Stanford"}}, false, true)
db.packages.update({"institution": "UTHSA (UTHSA/EMBL/PNNL/UCSD TIS)"}, {$set: {"tisName": "UTHSA/EMBL/PNNL/UCSD"}}, false, true)
db.packages.update({"institution": "WashU (UCSD/WashU TIS)"}, {$set: {"tisName": "UCSD/WashU"}}, false, true)
db.packages.update(\{ "isError": \{ $exists: false \} \}, \{$set: \{"regenerateZip": true\}‌\}, false, true)
db.packages.update({ packageType:"Bulk RNA-Seq" },{ $set:{ packageType:"Bulk total/mRNA", regenerateZip:true }‌}, false, true)
db.packages.update({ packageType:"Sub-segment RNA-Seq" },{ $set:{ packageType:"Sub-segmental RNA-Seq", regenerateZip:true }‌}, false, true)
